-- QUICK FIX: Add new car types to CAR_TYPE_ENUM
-- Run these commands directly in your PostgreSQL database (psql, pgAdmin, or any SQL client)

-- Connect to your database first, then run:

ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'SEDAN_4_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'NEW_SEDAN_2022_MODEL';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'ETIOS_4_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'SUV_6_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'SUV_7_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'INNOVA_6_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'INNOVA_7_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'INNOVA_CRYSTA_6_PLUS_1';
ALTER TYPE "CAR_TYPE_ENUM" ADD VALUE 'INNOVA_CRYSTA_7_PLUS_1';

-- Verify the values were added:
SELECT enumlabel 
FROM pg_enum 
WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'CAR_TYPE_ENUM')
ORDER BY enumsortorder;






